### DSC Week 7 & 8 
### Madison Christiansen

In [54]:
import pandas as pd
import numpy as np
candydf = pandas.read_excel('/Users/madisonchristiansen/Desktop/candyhierarchy2017.xlsx')
candydf

/Users/madisonchristiansen/opt/anaconda3/lib/python3.9/site-packages/openpyxl/worksheet/_read_only.py:79: UserWarning: Unknown extension is not supported and will be removed
  for idx, row in parser.parse():

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,Capers,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [57]:
## Remove duplicates
candydf = candydf.drop_duplicates(subset='Internal ID', keep="first")
candydf

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,Capers,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [58]:
## Filter out missing data - the column that has a lot of missing data 
candydf.isnull().sum().sort_values(ascending=False)
candydf = candydf.drop('Unnamed: 113', axis=1)

In [25]:
## Create hierarchical index
col = candydf.columns
df_ind = candydf.set_index(['Internal ID', 'Q4: COUNTRY', 'Q5: STATE, PROVINCE, COUNTY, ETC'])
df_ind.sort_index()

,,,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,Q6 | Bonkers (the candy),Q6 | Bonkers (the board game),Q6 | Bottle Caps,...,Q7: JOY OTHER,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
Internal ID,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",,,,,,,,,,,,,,,,,,,,,
90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272821,USA,NM,No,Male,44,MEH,DESPAIR,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,...,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
90272829,USA,Virginia,NaN,Male,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90272840,us,or,No,Male,40,MEH,DESPAIR,JOY,MEH,MEH,DESPAIR,MEH,...,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
90272841,usa,exton pa,No,Male,23,JOY,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,MEH,...,NaN,NaN,NaN,White and gold,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90314359,USA,MD,No,Male,24,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,MEH,MEH,...,Mounds,Fruit Stripe Gum,NaN,White and gold,Friday,NaN,NaN,NaN,NaN,NaN
90314580,USA,New York,No,Female,33,MEH,DESPAIR,JOY,NaN,NaN,NaN,NaN,...,NaN,Capers,NaN,Blue and black,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
90314634,USA,Tennessee,No,Female,26,MEH,DESPAIR,JOY,DESPAIR,MEH,JOY,DESPAIR,...,Tiny bottles of maple syrup as given out by Cr...,NaN,NaN,Blue and black,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
90314658,Usa,North Carolina,No,Male,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90314802,usa,Pennsylvania,No,Female,66,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,DESPAIR,...,NaN,NaN,"You hit all my chocolate highlights, and broug...",White and gold,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [27]:
## pivot
pivotdf = candydf.pivot(index='Internal ID', columns='Q6 | Any full-sized candy bar', values='Q9: OTHER COMMENTS')
pivotdf.head()

Q6 | Any full-sized candy bar,NaN,DESPAIR,JOY,MEH
Internal ID,,,,
90258773,NaN,NaN,NaN,NaN
90272821,NaN,NaN,Bottom line is Twix is really the only candy w...,NaN
90272829,NaN,NaN,NaN,NaN
90272840,NaN,NaN,Raisins can go to hell,NaN
90272841,NaN,NaN,NaN,NaN

In [39]:
## Split/Apply/Combine
## Grouping with Functions
myseries = pd.Series(
 data=['THREE', 'ONE', 'TWO'],
 index=['A', 'B', 'C']
)
def GROUP(grp):
 return myseries

grouped = candydf.groupby(['Q4: COUNTRY', 'Internal ID']).apply(func=GROUP)

grouped

                             A    B    C
Q4: COUNTRY Internal ID
1           90288589     THREE  ONE  TWO
32          90276056     THREE  ONE  TWO
35          90273290     THREE  ONE  TWO
45          90275804     THREE  ONE  TWO
46          90274626     THREE  ONE  TWO
...                        ...  ...  ...
usa         90311726     THREE  ONE  TWO
            90312849     THREE  ONE  TWO
            90313367     THREE  ONE  TWO
            90314802     THREE  ONE  TWO
usas        90275719     THREE  ONE  TWO

[2396 rows x 3 columns]

In [62]:
df2 = pandas.read_excel('/Users/madisonchristiansen/Desktop/BOING-BOING-CANDY-HIERARCHY-2016-SURVEY-Responses.xlsx')
df2

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [JK Rowling],Please estimate the degree(s) of separation you have from the following celebrities [JJ Abrams],Please estimate the degree(s) of separation you have from the following celebrities [Beyoncé],Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,"Actually, that's me.",3 or higher,3 or higher,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,1,2,3 or higher,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN

In [76]:
## Convert between string and date time
df2['New Timestamp'] = pd.to_datetime(df2['Timestamp'], format='%m%d%Y%H%M%S')
df2

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore,1,Period,New Timestamp
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:09:23.033
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:09:54.798
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:13:06.734
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:14:17.192
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN,2016-10,2016-10,2016-10-24 05:14:24.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-29 16:53:52.516
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-30 06:53:54.735
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-30 11:06:10.827
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-30 16:07:26.539
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN,2016-10,2016-10,2016-10-30 17:06:45.660

In [77]:
## Convert timestamps to periods and back - new period column
df2['Period'] = pd.DatetimeIndex(df2['Timestamp']).to_period('M')
df2

,Timestamp,Are you going actually going trick or treating yourself?,Your gender:,How old are you?,Which country do you live in?,"Which state, province, county do you live in?",[100 Grand Bar],[Anonymous brown globs that come in black and orange wrappers],[Any full-sized candy bar],[Black Jacks],...,Please estimate the degree(s) of separation you have from the following celebrities [Bieber],Please estimate the degree(s) of separation you have from the following celebrities [Kevin Bacon],Please estimate the degree(s) of separation you have from the following celebrities [Francis Bacon (1561 - 1626)],"Which day do you prefer, Friday or Sunday?","Do you eat apples the correct way, East to West (side to side) or do you eat them like a freak of nature, South to North (bottom to top)?","When you see the above image of the 4 different websites, which one would you most likely check out (please be honest).",[York Peppermint Patties] Ignore,1,Period,New Timestamp
0,2016-10-24 05:09:23.033,No,Male,22,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Friday,South to North,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:09:23.033
1,2016-10-24 05:09:54.798,No,Male,45,usa,il,MEH,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:09:54.798
2,2016-10-24 05:13:06.734,No,Female,48,US,Colorado,JOY,DESPAIR,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:13:06.734
3,2016-10-24 05:14:17.192,No,Male,57,usa,il,JOY,MEH,JOY,MEH,...,3 or higher,3 or higher,3 or higher,Sunday,South to North,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-24 05:14:17.192
4,2016-10-24 05:14:24.625,Yes,Male,42,USA,South Dakota,MEH,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,3 or higher,Friday,East to West,ESPN,NaN,2016-10,2016-10,2016-10-24 05:14:24.625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2016-10-29 16:53:52.516,No,Female,52,USA,TX,JOY,DESPAIR,JOY,MEH,...,3 or higher,2,3 or higher,Friday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-29 16:53:52.516
1255,2016-10-30 06:53:54.735,No,Male,33,united states,minnesota,JOY,DESPAIR,JOY,DESPAIR,...,3 or higher,3 or higher,"Actually, that's me.",Friday,Sinusoidally around the equator,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-30 06:53:54.735
1256,2016-10-30 11:06:10.827,No,Male,NaN,NaN,NaN,JOY,MEH,JOY,NaN,...,NaN,NaN,NaN,Sunday,nne to east to nnw to s to n,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-30 11:06:10.827
1257,2016-10-30 16:07:26.539,No,Male,48,canada,BC,NaN,DESPAIR,JOY,DESPAIR,...,3 or higher,2,3 or higher,Sunday,East to West,Science: Latest News and Headlines,NaN,2016-10,2016-10,2016-10-30 16:07:26.539
1258,2016-10-30 17:06:45.660,Yes,Female,44,Us,Nh,JOY,MEH,JOY,JOY,...,3 or higher,3 or higher,3 or higher,Sunday,East to West,Daily Dish,NaN,2016-10,2016-10,2016-10-30 17:06:45.660